# Generated by Django 6.0.4 on 2026-04-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('view_key', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left', 'Left'), ('right', 'Right'), ('detail', 'Detail')], max_length=20)),
                ('base_image', models.ImageField(upload_to='catalog/')),
                ('print_area_x', models.PositiveIntegerField()),
                ('print_area_y', models.PositiveIntegerField()),
                ('print_area_width', models.PositiveIntegerField()),
                ('print_area_height', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='customizer.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('product', 'view_key', 'label')},
            },
        ),
    ]
